### ISSUE TITLE
Switch event.deferReply().setContent to reply(event, ....)

### ISSUE THREAD

**Issue by DaRealTurtyWurty** [DaRealTurtyWurty/SuperTurtyBot#207]
A lot of the code was written before I added the `reply` method, and as such it is using `event.deferReply().setContent`, which is a lot more of a handful. 

So, ideally, at some point it would be nice to switch all of the code to be using the `reply` method in order to keep some consistency throughout.

All instances should be visible here:
https://github.com/search?q=repo%3ADaRealTurtyWurty%2FSuperTurtyBot%20event.deferReply&type=code

However, it is important to note that instances of `event.deferReply().queue()` and `event.deferReply(true).queue()` should be left alone.

**Comment by AlessioBugetti** [comment]
I am interested in addressing this issue and would appreciate being assigned to it.

There are some cases that seem unable to be replaced using the reply method, such as:

`event.deferReply().setFiles(FileUpload.fromData(connection.getInputStream(), statusCode + ".jpg"))`

In these cases, is it sufficient to leave `event.deferReply` left alone?
